FROM linuxserver/wireguard:latest

#install wireguard
RUN apk update && apk add curl wireguard-tools screen nftables sqlite~=3.40.1-r0 musl-dev build-base

#install golang & air
RUN curl -OL https://golang.org/dl/go1.19.4.linux-amd64.tar.gz && tar -C /usr/local -xvf go1.19.4.linux-amd64.tar.gz
RUN mkdir /lib64 && ln -s /lib/libc.musl-x86_64.so.1 /lib64/ld-linux-x86-64.so.2

ENV PATH=$PATH:/usr/local/go/bin
# where install libs
ENV GOPATH=/usr/local/go

#debug lib
RUN go install github.com/go-delve/delve/cmd/dlv@v1.20.1


RUN go install github.com/cosmtrek/air@latest

#RUN systemctl enable nftables.service
#RUN curl -L https://github.com/suquant/wgrest/releases/latest/download/wgrest_amd64.deb -o wgrest_amd64.deb
#RUN dpkg -i wgrest_amd64.deb

WORKDIR /home/wgrest

COPY ./run-dev.sh ./run-dev.sh

#COPY ./postup.sh ./postup.sh
#COPY ./postdown.sh ./postdown.sh

RUN chmod +x run-dev.sh

ENTRYPOINT exec ./run-dev.sh